/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projects;

import View.MainScreen;
// import Controller.ProjectController;
// import Controller.TaskController;
// import Model.Project;
// import Model.Task;
// import java.util.Date;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        /*
            ProjectController newProject = new ProjectController();
        
            Project project = new Project();

            project.setName("CRUD PHP");
            project.setDescription("Criar um CRUD utilizando a linguagem PHP");

            newProject.save(project);
        */
        
        /*
            TaskController newTask = new TaskController();
        
            Task task = new Task();

            task.setIdProject(1);
            task.setName("Create");
            task.setDescription("Criar o método save");
            task.setNotes("Sem notas, por enquanto!");
            task.setDeadline(new Date());

            newTask.save(task);
        */
        
        MainScreen screen = new MainScreen();
        screen.setVisible(true);
    }
}
