/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProjectController;
import Controller.TaskController;
import Model.Project;
import Model.Task;
import Util.ButtonRenderer;
import Util.DeadlineStatus;
import Util.TaskTableModel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author alexa
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;

    DefaultListModel projectsModel;
    TaskTableModel taskModel;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();

        initDataController();
        initComponentsModel();

        decorateTableTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollTable = new javax.swing.JScrollPane();
        TableTasks = new javax.swing.JTable();
        MainPanel = new javax.swing.JPanel();
        Toolbar = new javax.swing.JPanel();
        ToolbarTitle = new javax.swing.JLabel();
        Projects = new javax.swing.JPanel();
        ProjectsTitle = new javax.swing.JLabel();
        ProjectsBtn = new javax.swing.JLabel();
        Tasks = new javax.swing.JPanel();
        TasksTitle = new javax.swing.JLabel();
        TasksBtn = new javax.swing.JLabel();
        List = new javax.swing.JPanel();
        ScrollList = new javax.swing.JScrollPane();
        ListProjects = new javax.swing.JList<>();
        Table = new javax.swing.JPanel();
        NoTasksContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        ScrollTable.setBorder(null);

        TableTasks.setBackground(new java.awt.Color(162, 151, 195));
        TableTasks.setFont(new java.awt.Font("Fira Code Retina", 0, 18)); // NOI18N
        TableTasks.setForeground(new java.awt.Color(255, 255, 255));
        TableTasks.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Nome", "Descrição", "Prazo", "Status"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        TableTasks.setGridColor(new java.awt.Color(162, 151, 195));
        TableTasks.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableTasks.setRowHeight(60);
        TableTasks.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TableTasks.setSelectionForeground(new java.awt.Color(98, 86, 130));
        TableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableTasks.setShowGrid(false);
        TableTasks.setShowHorizontalLines(true);
        TableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTasksMouseClicked(evt);
            }
        });
        ScrollTable.setViewportView(TableTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(600, 600));

        MainPanel.setBackground(new java.awt.Color(162, 151, 195));

        Toolbar.setBackground(new java.awt.Color(98, 86, 130));
        Toolbar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ToolbarTitle.setFont(new java.awt.Font("Fira Code", 1, 36)); // NOI18N
        ToolbarTitle.setForeground(new java.awt.Color(255, 255, 255));
        ToolbarTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToolbarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/check.png"))); // NOI18N
        ToolbarTitle.setText("Projects");

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
                ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(ToolbarTitle, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50)));
        ToolbarLayout.setVerticalGroup(
                ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                                .addContainerGap(24, Short.MAX_VALUE)
                                .addComponent(ToolbarTitle)
                                .addGap(23, 23, 23)));

        Projects.setBackground(new java.awt.Color(162, 151, 195));
        Projects.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ProjectsTitle.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        ProjectsTitle.setForeground(new java.awt.Color(255, 255, 255));
        ProjectsTitle.setText("Projetos");

        ProjectsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        ProjectsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProjectsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProjectsBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProjectsLayout = new javax.swing.GroupLayout(Projects);
        Projects.setLayout(ProjectsLayout);
        ProjectsLayout.setHorizontalGroup(
                ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ProjectsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProjectsBtn)
                                .addGap(14, 14, 14)));
        ProjectsLayout.setVerticalGroup(
                ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectsLayout.createSequentialGroup()
                                .addContainerGap(26, Short.MAX_VALUE)
                                .addGroup(ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ProjectsBtn)
                                        .addComponent(ProjectsTitle))
                                .addGap(26, 26, 26)));

        Tasks.setBackground(new java.awt.Color(162, 151, 195));
        Tasks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TasksTitle.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        TasksTitle.setForeground(new java.awt.Color(255, 255, 255));
        TasksTitle.setText("Tarefas");

        TasksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        TasksBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TasksBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TasksBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TasksLayout = new javax.swing.GroupLayout(Tasks);
        Tasks.setLayout(TasksLayout);
        TasksLayout.setHorizontalGroup(
                TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TasksLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 407,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TasksBtn)
                                .addGap(15, 15, 15)));
        TasksLayout.setVerticalGroup(
                TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TasksLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TasksBtn)
                                        .addComponent(TasksTitle))
                                .addGap(25, 25, 25)));

        List.setBackground(new java.awt.Color(162, 151, 195));
        List.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ListProjects.setBackground(new java.awt.Color(98, 86, 130));
        ListProjects.setBorder(null);
        ListProjects.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        ListProjects.setForeground(new java.awt.Color(255, 255, 255));
        ListProjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListProjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListProjects.setFixedCellHeight(40);
        ListProjects.setSelectionBackground(new java.awt.Color(255, 255, 255));
        ListProjects.setSelectionForeground(new java.awt.Color(98, 86, 130));
        ListProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListProjectsMouseClicked(evt);
            }
        });
        ScrollList.setViewportView(ListProjects);

        javax.swing.GroupLayout ListLayout = new javax.swing.GroupLayout(List);
        List.setLayout(ListLayout);
        ListLayout.setHorizontalGroup(
                ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ListLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ScrollList, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addContainerGap()));
        ListLayout.setVerticalGroup(
                ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ScrollList)
                                .addContainerGap()));

        Table.setBackground(new java.awt.Color(162, 151, 195));
        Table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table.setLayout(new java.awt.BorderLayout(15, 15));

        NoTasksContainer.setBackground(new java.awt.Color(162, 151, 195));

        jLabel1.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/notes.png"))); // NOI18N
        jLabel1.setText("Sem tarefas cadastradas");

        javax.swing.GroupLayout NoTasksContainerLayout = new javax.swing.GroupLayout(NoTasksContainer);
        NoTasksContainer.setLayout(NoTasksContainerLayout);
        NoTasksContainerLayout.setHorizontalGroup(
                NoTasksContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NoTasksContainerLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                .addGap(125, 125, 125)));
        NoTasksContainerLayout.setVerticalGroup(
                NoTasksContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                NoTasksContainerLayout.createSequentialGroup()
                                        .addGap(193, 193, 193)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116,
                                                Short.MAX_VALUE)
                                        .addGap(193, 193, 193)));

        Table.add(NoTasksContainer, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MainPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Projects, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(List, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tasks, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Table, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Projects, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tasks, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(List, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Table, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProjectsBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ProjectsBtnMouseClicked
        // TODO add your handling code here:
        CreateProjectScreen screen = new CreateProjectScreen(this, rootPaneCheckingEnabled);
        screen.setVisible(true);

        screen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent evt) {
                loadProjects();
            }
        });
    }// GEN-LAST:event_ProjectsBtnMouseClicked

    private void TasksBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TasksBtnMouseClicked
        // TODO add your handling code here:
        CreateTaskScreen screen = new CreateTaskScreen(this, rootPaneCheckingEnabled);

        // screen.setProject(null);

        int projectIndex = ListProjects.getSelectedIndex();

        Project project = (Project) projectsModel.get(projectIndex);

        screen.setProject(project);

        screen.setVisible(true);

        screen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent evt) {
                int projectIndex = ListProjects.getSelectedIndex();

                Project project = (Project) projectsModel.get(projectIndex);

                loadTasks(project.getId());
            }
        });
    }// GEN-LAST:event_TasksBtnMouseClicked

    private void ListProjectsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ListProjectsMouseClicked
        // TODO add your handling code here:
        int projectIndex = ListProjects.getSelectedIndex();

        Project project = (Project) projectsModel.get(projectIndex);

        loadTasks(project.getId());
    }// GEN-LAST:event_ListProjectsMouseClicked

    private void TableTasksMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TableTasksMouseClicked
        // TODO add your handling code here:
        int rowIndex = TableTasks.rowAtPoint(evt.getPoint());
        int columnIndex = TableTasks.columnAtPoint(evt.getPoint());

        Task task = taskModel.getTasks().get(rowIndex);

        switch (columnIndex) {
            case 3:
                taskController.update(task);
                break;
            case 5:
                taskController.removeById(task.getId());
                taskModel.getTasks().remove(task);

                int projectIndex = ListProjects.getSelectedIndex();
                Project project = (Project) projectsModel.get(projectIndex);

                loadTasks(project.getId());
                break;
        }
    }// GEN-LAST:event_TableTasksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel List;
    private javax.swing.JList<String> ListProjects;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel NoTasksContainer;
    private javax.swing.JPanel Projects;
    private javax.swing.JLabel ProjectsBtn;
    private javax.swing.JLabel ProjectsTitle;
    private javax.swing.JScrollPane ScrollList;
    private javax.swing.JScrollPane ScrollTable;
    private javax.swing.JPanel Table;
    private javax.swing.JTable TableTasks;
    private javax.swing.JPanel Tasks;
    private javax.swing.JLabel TasksBtn;
    private javax.swing.JLabel TasksTitle;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JLabel ToolbarTitle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTask() {
        TableTasks.getTableHeader().setFont(new Font("Fira Code Retina", Font.BOLD, 18));

        TableTasks.getTableHeader().setBackground(new Color(98, 86, 130));

        TableTasks.getTableHeader().setForeground(new Color(255, 255, 255));

        // TableTasks.setAutoCreateRowSorter(true);

        TableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineStatus());

        TableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer("edit"));

        TableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer("delete"));
    }

    public void initDataController() {
        projectController = new ProjectController();
        taskController = new TaskController();
    }

    public void initComponentsModel() {
        projectsModel = new DefaultListModel();
        loadProjects();

        taskModel = new TaskTableModel();
        TableTasks.setModel(taskModel);

        if (!projectsModel.isEmpty()) {
            ListProjects.setSelectedIndex(0);

            Project project = (Project) projectsModel.get(0);

            loadTasks(project.getId());
        }
    }

    public void loadProjects() {
        List<Project> projects = projectController.getAll();

        projectsModel.clear();

        for (int i = 0; i < projects.size(); i++) {
            Project project = projects.get(i);

            projectsModel.addElement(project);
        }

        ListProjects.setModel(projectsModel);
    }

    public void loadTasks(int projectId) {
        List<Task> tasks = taskController.getAll(projectId);

        taskModel.setTasks(tasks);

        showTableTasks(!tasks.isEmpty());
    }

    private void showTableTasks(boolean hasTasks) {
        if (hasTasks) {
            if (NoTasksContainer.isVisible()) {
                NoTasksContainer.setVisible(false);
                Table.remove(NoTasksContainer);
            }

            Table.add(ScrollTable);
            ScrollTable.setVisible(true);
            ScrollTable.setSize(Table.getWidth(), Table.getHeight());
        } else {
            if (ScrollTable.isVisible()) {
                ScrollTable.setVisible(false);
                Table.remove(ScrollTable);
            }

            Table.add(NoTasksContainer);
            NoTasksContainer.setVisible(true);
            NoTasksContainer.setSize(Table.getWidth(), Table.getHeight());
        }
    }
}
